### ISSUE TITLE
error[E0425]: cannot find value `DEPENDENCIES_STR` in module `built_info`

### ISSUE THREAD

**Issue by xftroxgpx** [lukaslueg/built#10]
```toml
[package]
name = "built_example"
version = "0.1.0"


[dependencies]

#src: https://docs.rs/built/0.2.3/built/?search=
[build-dependencies]
built = "0.2"          
```

Does this mean that if the `[dependencies]` list is empty, the `DEPENDENCIES_STR` is undefined? Should it maybe be defined but empty?

I notice the right thing happens for `authors` though:
```rust
#[doc="A colon-separated list of authors."]                                     
pub const PKG_AUTHORS: &'static str = "";
```
